# -*- coding: utf-8 -*-
"""multiplechoice-chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QffYO6WbQl3iXKhAcus6g48FqU7gotAf
"""

# https://huggingface.co/datasets/bigbio/med_qa/blob/main/med_qa.py



!pip install datasets

import datasets
import pandas as pd

raw_data = datasets.load_dataset("bigbio/med_qa")

raw_data.keys()

df = pd.DataFrame(raw_data['train'])

df.head()

question = df['question'].iloc[0]

opts = df['options'].iloc[0]

question1 = df['question'].iloc[1]

options1 = df['options'].iloc[1]

print(question1, options1)



df['options'].iloc[0]

def getkeysandvalues(question, options):
  data1 = ""
  for i in options:
    data1 = data1 + i['key'] + ") " +i['value'] + ' '
    # print(options)
  final = question + data1
  return final

secondQuestions = getkeysandvalues(question1, options1)
second_answer = "A"

firstQuestion = getkeysandvalues(question,opts)

print(firstQuestion)

first_answer = "E"

system_role = "You are a helpful assistant that answers multiple choice questions about medical knowledge."

!pip install openai==0.28

import openai

openai.api_key=""

def get_response(messages,model="gpt-3.5-turbo"):
  response = openai.ChatCompletion.create(
        model=model,
        messages=messages
     )
  return response.choices[0].message["content"]

user_prompt = f'''Question:{firstQuestion}
Answer:{first_answer}

Question:{secondQuestions}
Answer:
'''

messages=[{'role':'system','content':system_role},
          {'role':'user','content':user_prompt}
          ]

print(get_response(messages))

def get_response_four(messages,model="gpt-4-turbo"):
  response = openai.ChatCompletion.create(
        model=model,
        messages=messages
     )
  return response.choices[0].message["content"]

# print(get_response_four(messages))